"""Tests for the contradiction lock state machine.

Verifies:
- PostToolUse hook creates .smm/contradiction.lock when contradictions found
- PreToolUse hook blocks Write/Edit when lock exists
- PreToolUse hook blocks agent self-resolve (vt check --resolve, vt resolve)
- PreToolUse hook allows non-resolve Bash commands when locked
- PreToolUse hook allows Write/Edit when no lock exists
- Dashboard resolution deletes the lock file
- CLI resolution deletes the lock file
- Lock file has correct JSON format
- install_claude_code_hook generates hooks with lock support
- Settings include Bash in PreToolUse matcher
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest


# ---------------------------------------------------------------------------
# Hook script content tests (generated by install_claude_code_hook)
# ---------------------------------------------------------------------------


class TestPreToolUseHookLockSupport:
    """Verify the PreToolUse hook template includes lock file checking."""

    def _get_hook_content(self, tmp_path: Path) -> str:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        install_claude_code_hook(root)
        return (root / ".claude" / "hooks" / "vt-validate.sh").read_text()

    def test_hook_checks_contradiction_lock(self, tmp_path: Path) -> None:
        content = self._get_hook_content(tmp_path)
        assert "contradiction.lock" in content

    def test_hook_blocks_write_when_locked(self, tmp_path: Path) -> None:
        content = self._get_hook_content(tmp_path)
        assert "BLOCKED: Unresolved contradiction" in content

    def test_hook_blocks_self_resolve_bash(self, tmp_path: Path) -> None:
        content = self._get_hook_content(tmp_path)
        assert "Agent cannot self-resolve" in content
        assert 'vt (check --resolve|resolve)' in content

    def test_hook_checks_lock_before_validation(self, tmp_path: Path) -> None:
        """Lock check must come before vt validate-change."""
        content = self._get_hook_content(tmp_path)
        lock_pos = content.find("contradiction.lock")
        validate_pos = content.find("vt validate-change")
        assert lock_pos < validate_pos, "Lock check must precede validation"

    def test_hook_allows_other_bash_when_locked(self, tmp_path: Path) -> None:
        """Non-resolve Bash commands should pass through even when locked."""
        content = self._get_hook_content(tmp_path)
        # After blocking self-resolve, there's a comment about allowing other Bash
        assert "Allow other Bash commands" in content


class TestPostToolUseHookLockCreation:
    """Verify the PostToolUse hook template creates lock files."""

    def _get_hook_content(self, tmp_path: Path) -> str:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        install_claude_code_hook(root)
        return (root / ".claude" / "hooks" / "vt-post-write.sh").read_text()

    def test_hook_creates_lock_on_contradiction(self, tmp_path: Path) -> None:
        content = self._get_hook_content(tmp_path)
        assert "contradiction.lock" in content

    def test_hook_writes_lock_with_jq(self, tmp_path: Path) -> None:
        content = self._get_hook_content(tmp_path)
        assert "contradiction_id" in content
        assert "detected_at" in content
        assert "description" in content

    def test_hook_scans_contradiction_files_for_id(self, tmp_path: Path) -> None:
        content = self._get_hook_content(tmp_path)
        assert "contradictions/contradiction-*.json" in content

    def test_hook_state_machine_comment(self, tmp_path: Path) -> None:
        content = self._get_hook_content(tmp_path)
        assert "STATE MACHINE" in content


class TestSettingsBashMatcher:
    """Verify settings.json includes Bash in PreToolUse matcher."""

    def test_matcher_includes_bash(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        install_claude_code_hook(root)

        settings = json.loads((root / ".claude" / "settings.json").read_text())
        pre_hooks = settings["hooks"]["PreToolUse"]
        matchers = [h.get("matcher") for h in pre_hooks]
        assert any("Bash" in m for m in matchers), "PreToolUse must match Bash tool"

    def test_matcher_still_includes_write_edit(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        install_claude_code_hook(root)

        settings = json.loads((root / ".claude" / "settings.json").read_text())
        pre_hooks = settings["hooks"]["PreToolUse"]
        matchers = [h.get("matcher") for h in pre_hooks]
        assert any("Write" in m and "Edit" in m for m in matchers)


# ---------------------------------------------------------------------------
# Live hook script tests (run the actual bash scripts)
# ---------------------------------------------------------------------------


class TestPreToolUseHookExecution:
    """Run the actual vt-validate.sh hook script and verify behavior."""

    def _run_hook(self, tmp_path: Path, input_json: dict) -> subprocess.CompletedProcess:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        (root / ".smm").mkdir()
        (root / ".smm" / "traces").mkdir(parents=True, exist_ok=True)
        install_claude_code_hook(root)

        hook = root / ".claude" / "hooks" / "vt-validate.sh"
        return subprocess.run(
            ["bash", str(hook)],
            input=json.dumps(input_json),
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=10,
        )

    def test_allows_write_when_no_lock(self, tmp_path: Path) -> None:
        result = self._run_hook(tmp_path, {
            "tool_name": "Write",
            "tool_input": {"file_path": "/tmp/test.py", "content": "x = 1"},
        })
        # Should not deny (vt command likely not installed in test env)
        if result.stdout.strip():
            output = json.loads(result.stdout)
            # If there's output, it shouldn't be a lock-based denial
            reason = (
                output.get("hookSpecificOutput", {})
                .get("permissionDecisionReason", "")
            )
            assert "Unresolved contradiction" not in reason

    def test_blocks_write_when_lock_exists(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        (smm / "traces").mkdir()
        install_claude_code_hook(root)

        # Create lock file
        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({
            "contradiction_id": "test-123",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "NoSQL vs Relational",
            "message": "Resolve via dashboard",
        }))

        hook = root / ".claude" / "hooks" / "vt-validate.sh"
        result = subprocess.run(
            ["bash", str(hook)],
            input=json.dumps({
                "tool_name": "Write",
                "tool_input": {"file_path": "/tmp/test.py", "content": "x = 1"},
            }),
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=10,
        )
        assert result.returncode == 0
        output = json.loads(result.stdout)
        decision = output["hookSpecificOutput"]["permissionDecision"]
        reason = output["hookSpecificOutput"]["permissionDecisionReason"]
        assert decision == "deny"
        assert "Unresolved contradiction" in reason

    def test_blocks_edit_when_lock_exists(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        (smm / "traces").mkdir()
        install_claude_code_hook(root)

        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({
            "contradiction_id": "test-456",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "Test",
            "message": "Resolve via dashboard",
        }))

        hook = root / ".claude" / "hooks" / "vt-validate.sh"
        result = subprocess.run(
            ["bash", str(hook)],
            input=json.dumps({
                "tool_name": "Edit",
                "tool_input": {
                    "file_path": "/tmp/test.py",
                    "old_string": "x = 1",
                    "new_string": "x = 2",
                },
            }),
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=10,
        )
        output = json.loads(result.stdout)
        assert output["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_blocks_vt_resolve_bash_when_locked(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        (smm / "traces").mkdir()
        install_claude_code_hook(root)

        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({
            "contradiction_id": "test-789",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "Test",
            "message": "Resolve via dashboard",
        }))

        hook = root / ".claude" / "hooks" / "vt-validate.sh"
        result = subprocess.run(
            ["bash", str(hook)],
            input=json.dumps({
                "tool_name": "Bash",
                "tool_input": {"command": "vt check --resolve"},
            }),
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=10,
        )
        output = json.loads(result.stdout)
        assert output["hookSpecificOutput"]["permissionDecision"] == "deny"
        assert "self-resolve" in output["hookSpecificOutput"]["permissionDecisionReason"]

    def test_blocks_vt_resolve_command_when_locked(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        (smm / "traces").mkdir()
        install_claude_code_hook(root)

        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({
            "contradiction_id": "test-000",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "Test",
            "message": "Resolve via dashboard",
        }))

        hook = root / ".claude" / "hooks" / "vt-validate.sh"
        result = subprocess.run(
            ["bash", str(hook)],
            input=json.dumps({
                "tool_name": "Bash",
                "tool_input": {"command": "vt resolve --path ."},
            }),
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=10,
        )
        output = json.loads(result.stdout)
        assert output["hookSpecificOutput"]["permissionDecision"] == "deny"

    def test_allows_other_bash_when_locked(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        (smm / "traces").mkdir()
        install_claude_code_hook(root)

        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({
            "contradiction_id": "test-111",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "Test",
            "message": "Resolve via dashboard",
        }))

        hook = root / ".claude" / "hooks" / "vt-validate.sh"
        result = subprocess.run(
            ["bash", str(hook)],
            input=json.dumps({
                "tool_name": "Bash",
                "tool_input": {"command": "git status"},
            }),
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=10,
        )
        # Should produce no output (exit 0, no deny JSON)
        assert result.stdout.strip() == ""
        assert result.returncode == 0

    def test_allows_read_tool_when_locked(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        (smm / "traces").mkdir()
        install_claude_code_hook(root)

        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({
            "contradiction_id": "test-222",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "Test",
            "message": "Resolve via dashboard",
        }))

        hook = root / ".claude" / "hooks" / "vt-validate.sh"
        result = subprocess.run(
            ["bash", str(hook)],
            input=json.dumps({
                "tool_name": "Read",
                "tool_input": {"file_path": "/tmp/test.py"},
            }),
            capture_output=True,
            text=True,
            cwd=str(root),
            timeout=10,
        )
        # Read tool should pass through (exit 0, no deny)
        assert result.stdout.strip() == ""
        assert result.returncode == 0


# ---------------------------------------------------------------------------
# Dashboard lock deletion tests
# ---------------------------------------------------------------------------


class TestDashboardLockDeletion:
    """Verify dashboard resolution endpoints delete the lock file."""

    @pytest.fixture()
    def project_with_lock(self, tmp_path: Path) -> Path:
        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        (smm / "decisions").mkdir()
        (smm / "contradictions").mkdir()
        (smm / "traces").mkdir()
        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({
            "contradiction_id": "abc123",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "Test",
            "message": "Resolve via dashboard",
        }))
        return root

    def test_delete_contradiction_lock_removes_file(self, project_with_lock: Path) -> None:
        from vt_protocol.dashboard.app import _delete_contradiction_lock

        lock = project_with_lock / ".smm" / "contradiction.lock"
        assert lock.exists()
        _delete_contradiction_lock(project_with_lock)
        assert not lock.exists()

    def test_delete_contradiction_lock_noop_when_missing(self, tmp_path: Path) -> None:
        from vt_protocol.dashboard.app import _delete_contradiction_lock

        root = tmp_path / "proj"
        root.mkdir()
        (root / ".smm").mkdir()
        # Should not raise
        _delete_contradiction_lock(root)


# ---------------------------------------------------------------------------
# CLI lock deletion tests
# ---------------------------------------------------------------------------


class TestCLILockDeletion:
    """Verify CLI resolution deletes the lock file."""

    def test_delete_contradiction_lock_removes_file(self, tmp_path: Path) -> None:
        from vt_protocol.cli.commands import _delete_contradiction_lock

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({"contradiction_id": "test"}))

        assert lock.exists()
        _delete_contradiction_lock(root)
        assert not lock.exists()

    def test_delete_contradiction_lock_noop_when_missing(self, tmp_path: Path) -> None:
        from vt_protocol.cli.commands import _delete_contradiction_lock

        root = tmp_path / "proj"
        root.mkdir()
        (root / ".smm").mkdir()
        # Should not raise
        _delete_contradiction_lock(root)

    def test_resolve_interactive_deletes_lock(self, tmp_path: Path) -> None:
        """After interactive resolution, lock should be deleted."""
        from vt_protocol.cli.commands import _delete_contradiction_lock

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        lock = smm / "contradiction.lock"
        lock.write_text(json.dumps({"contradiction_id": "test"}))

        # Simulate what _resolve_contradictions_interactive does at the end
        _delete_contradiction_lock(root)
        assert not lock.exists()


# ---------------------------------------------------------------------------
# Lock file format tests
# ---------------------------------------------------------------------------


class TestLockFileFormat:
    """Verify the lock file has the expected JSON structure."""

    def test_lock_file_has_required_fields(self, tmp_path: Path) -> None:
        lock = tmp_path / "contradiction.lock"
        lock_data = {
            "contradiction_id": "abc123",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "NoSQL Database vs Relational Database",
            "message": "Resolve via dashboard or 'vt check --resolve'",
        }
        lock.write_text(json.dumps(lock_data))

        loaded = json.loads(lock.read_text())
        assert "contradiction_id" in loaded
        assert "detected_at" in loaded
        assert "description" in loaded
        assert "message" in loaded

    def test_lock_file_is_valid_json(self, tmp_path: Path) -> None:
        lock = tmp_path / "contradiction.lock"
        lock_data = {
            "contradiction_id": "test-id",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "A vs B",
            "message": "Resolve via dashboard",
        }
        lock.write_text(json.dumps(lock_data))
        # Should not raise
        json.loads(lock.read_text())


# ---------------------------------------------------------------------------
# End-to-end state machine flow test
# ---------------------------------------------------------------------------


class TestStateMachineFlow:
    """Test the full CLEAN → CONTRADICTION_DETECTED → RESOLVED → CLEAN flow."""

    def test_full_flow(self, tmp_path: Path) -> None:
        from vt_protocol.integrations.git_hooks import install_claude_code_hook

        root = tmp_path / "proj"
        root.mkdir()
        smm = root / ".smm"
        smm.mkdir()
        (smm / "traces").mkdir()
        (smm / "contradictions").mkdir()
        install_claude_code_hook(root)

        hook = root / ".claude" / "hooks" / "vt-validate.sh"
        lock = smm / "contradiction.lock"

        write_input = json.dumps({
            "tool_name": "Write",
            "tool_input": {"file_path": "/tmp/test.py", "content": "x = 1"},
        })

        # STATE: CLEAN — writes should pass
        r1 = subprocess.run(
            ["bash", str(hook)], input=write_input,
            capture_output=True, text=True, cwd=str(root), timeout=10,
        )
        assert "deny" not in r1.stdout

        # Simulate PostToolUse creating lock (CONTRADICTION_DETECTED)
        lock.write_text(json.dumps({
            "contradiction_id": "flow-test",
            "detected_at": "2026-04-14T09:00:00Z",
            "description": "A vs B",
            "message": "Resolve via dashboard",
        }))

        # STATE: CONTRADICTION_DETECTED — writes should be blocked
        r2 = subprocess.run(
            ["bash", str(hook)], input=write_input,
            capture_output=True, text=True, cwd=str(root), timeout=10,
        )
        output2 = json.loads(r2.stdout)
        assert output2["hookSpecificOutput"]["permissionDecision"] == "deny"

        # STATE: CONTRADICTION_DETECTED — self-resolve should be blocked
        r3 = subprocess.run(
            ["bash", str(hook)],
            input=json.dumps({
                "tool_name": "Bash",
                "tool_input": {"command": "vt check --resolve"},
            }),
            capture_output=True, text=True, cwd=str(root), timeout=10,
        )
        output3 = json.loads(r3.stdout)
        assert output3["hookSpecificOutput"]["permissionDecision"] == "deny"

        # Human resolves — delete lock (RESOLVED → CLEAN)
        lock.unlink()

        # STATE: CLEAN — writes should pass again
        r4 = subprocess.run(
            ["bash", str(hook)], input=write_input,
            capture_output=True, text=True, cwd=str(root), timeout=10,
        )
        assert "deny" not in r4.stdout
