"""AGENTS.md generator — universal cross-tool baseline.

Generates a plain Markdown AGENTS.md file that any AI agent can consume.
This is the lowest-common-denominator format — no YAML frontmatter, no
tool-specific syntax.

From SPEC: "Auto-generate AGENTS.md — universal cross-tool baseline."
"""

from __future__ import annotations

from vt_protocol.prevention.priority import ScoredDecision


def generate_agents_md(scored: list[ScoredDecision], project_name: str = "") -> str:
    """Generate AGENTS.md content from scored decisions.

    Includes "always" tier decisions as primary rules, plus a summary
    of "auto" tier decisions for reference. Outputs imperative constraints.
    """
    always = [sd for sd in scored if sd.tier == "always"]
    auto = [sd for sd in scored if sd.tier == "auto"]

    lines: list[str] = []
    lines.append(f"# AGENTS.md — {project_name or 'Project'}")
    lines.append("")
    lines.append("<!-- Generated by VT Protocol. Do not edit manually. -->")
    lines.append("<!-- Regenerate with: vt apply -->")
    lines.append("")
    lines.append("## Instructions for AI Agents")
    lines.append("")
    lines.append("IMPORTANT: The following rules are binding governance constraints.")
    lines.append("Follow them when making changes. Do not deviate without explicit approval.")
    lines.append("")

    if not always and not auto:
        lines.append("No architectural decisions recorded yet.")
        return "\n".join(lines)

    # Always-active rules — imperative constraints
    if always:
        lines.append("## Core Rules (Always Active)")
        lines.append("")
        for i, sd in enumerate(always, 1):
            d = sd.decision
            if d.constraints:
                rule_text = d.constraints[0]
            else:
                rule_text = d.content.strip().replace("\n", " ")
                if len(rule_text) > 200:
                    rule_text = rule_text[:197] + "..."
            lines.append(f"{i}. {rule_text}")
        lines.append("")

    # Auto-attached rules (summary)
    if auto:
        lines.append("## Context-Specific Rules")
        lines.append("")
        lines.append("These rules apply when working in specific areas:")
        lines.append("")
        for sd in auto:
            d = sd.decision
            if d.constraints:
                rule_text = d.constraints[0]
            else:
                rule_text = d.content.strip().replace("\n", " ")
                if len(rule_text) > 200:
                    rule_text = rule_text[:197] + "..."
            dims = ", ".join(dim.value for dim in d.dimensions)
            lines.append(f"- {rule_text} *(applies to: {dims})*")
        lines.append("")

    return "\n".join(lines)
