"""CLAUDE.md + .claude/rules/ generator.

Generates agent instruction files for Claude Code from the decision graph.
Supports YAML frontmatter for .claude/rules/*.md files with path-based activation.

From SPEC: "Auto-generate CLAUDE.md from decision graph — select only decisions
relevant to current task, compact imperative instructions."
"""

from __future__ import annotations

from pathlib import Path

from vt_protocol.prevention.priority import ScoredDecision


def generate_claude_md(scored: list[ScoredDecision], project_name: str = "") -> str:
    """Generate CLAUDE.md content from scored decisions.

    Only includes "always" tier decisions in the main CLAUDE.md.
    """
    always = [sd for sd in scored if sd.tier == "always"]

    lines: list[str] = []
    lines.append(f"# CLAUDE.md — {project_name or 'Project'} Governance Rules")
    lines.append("")
    lines.append("<!-- Generated by VT Protocol. Do not edit manually. -->")
    lines.append("<!-- Regenerate with: vt apply -->")
    lines.append("")

    if not always:
        lines.append("No architectural decisions recorded yet. Run `vt init` to scan your project.")
        return "\n".join(lines)

    lines.append("## Architectural Decisions")
    lines.append("")
    for sd in always:
        d = sd.decision
        dims = ", ".join(dim.value for dim in d.dimensions)
        lines.append(f"### {d.title}")
        lines.append("")
        lines.append(f"**Dimensions:** {dims}")
        lines.append(f"**Type:** {d.decision_type.value} | **Confidence:** {d.confidence:.0%}")
        lines.append("")
        # Compact imperative instruction
        content = d.content.strip()
        if len(content) > 300:
            content = content[:297] + "..."
        lines.append(content)
        if d.rationale:
            lines.append("")
            lines.append(f"**Why:** {d.rationale}")
        if d.constraints:
            lines.append("")
            lines.append(f"**Constraints:** {', '.join(d.constraints)}")
        lines.append("")

    return "\n".join(lines)


def generate_claude_rules(scored: list[ScoredDecision], output_dir: Path) -> list[Path]:
    """Generate .claude/rules/*.md files for auto-attached decisions.

    Each file has YAML frontmatter with path globs for activation.
    Returns list of generated file paths.
    """
    auto = [sd for sd in scored if sd.tier == "auto" and sd.globs]
    output_dir.mkdir(parents=True, exist_ok=True)

    paths: list[Path] = []
    for sd in auto:
        d = sd.decision
        slug = d.title.lower().replace(" ", "-")[:50]
        slug = "".join(c for c in slug if c.isalnum() or c == "-")
        filename = f"{slug}.md"
        filepath = output_dir / filename

        globs_yaml = "\n".join(f'  - "{g}"' for g in sd.globs[:5])
        content = d.content.strip()
        if len(content) > 300:
            content = content[:297] + "..."

        text = (
            f"---\n"
            f"description: \"{d.title}\"\n"
            f"globs:\n{globs_yaml}\n"
            f"alwaysApply: false\n"
            f"---\n\n"
            f"# {d.title}\n\n"
            f"{content}\n"
        )
        filepath.write_text(text)
        paths.append(filepath)

    return paths
