"""Tests for RuleSync orchestration and providers."""

from __future__ import annotations

from pathlib import Path

import pytest

from vt_protocol.decisions.models import (
    Decision,
    DecisionType,
    Dimension,
    GovernanceConfig,
    SourceType,
)
from vt_protocol.prevention.providers.agents_md import generate_agents_md
from vt_protocol.prevention.providers.claude import generate_claude_md, generate_claude_rules
from vt_protocol.prevention.providers.cursor import generate_cursor_rules
from vt_protocol.prevention.priority import assign_tiers
from vt_protocol.prevention.rulesync import (
    _GOVERNANCE_END,
    _GOVERNANCE_START,
    _write_root_agent_file,
    _write_root_claude_md,
    sync_rules,
)


def _make_decision(title: str, dimensions: list[Dimension] | None = None) -> Decision:
    return Decision(
        title=title,
        content=f"Decision about {title}. This is the full description.",
        rationale=f"Because {title} is the best choice.",
        decision_type=DecisionType.ARCHITECTURAL,
        dimensions=dimensions or [Dimension.DATABASE],
        made_by="test",
        project="test-project",
        source_type=SourceType.MANUAL,
    )


@pytest.fixture
def decisions() -> list[Decision]:
    return [
        _make_decision("Use PostgreSQL", [Dimension.DATABASE]),
        _make_decision("REST API with FastAPI", [Dimension.API_STYLE]),
        _make_decision("JWT authentication", [Dimension.AUTH, Dimension.SECURITY]),
        _make_decision("Redis for caching", [Dimension.CACHING]),
        _make_decision("Docker deployment", [Dimension.DEPLOYMENT]),
    ]


@pytest.fixture
def config() -> GovernanceConfig:
    return GovernanceConfig(
        agents={"claude": True, "cursor": True, "copilot": True},
    )


class TestGenerateClaudeMd:
    def test_generates_content(self, decisions: list[Decision]) -> None:
        scored = assign_tiers(decisions, always_count=3)
        content = generate_claude_md(scored, project_name="test-project")
        assert "# CLAUDE.md" in content
        assert "test-project" in content
        assert "Generated by VT Protocol" in content

    def test_includes_always_decisions(self, decisions: list[Decision]) -> None:
        scored = assign_tiers(decisions, always_count=5)
        content = generate_claude_md(scored)
        for d in decisions:
            assert d.title in content

    def test_empty_decisions(self) -> None:
        content = generate_claude_md([], project_name="empty")
        assert "No architectural decisions" in content

    def test_includes_constraint_text(self, decisions: list[Decision]) -> None:
        scored = assign_tiers(decisions, always_count=5)
        content = generate_claude_md(scored)
        # Non-constraint decisions fall back to d.content
        assert "Decision about Use PostgreSQL" in content

    def test_includes_constraint_when_present(self) -> None:
        d = Decision(
            title="Use SQLite",
            content="Auto-detected",
            rationale="Scanned",
            constraints=["This project uses SQLite. Do not introduce PostgreSQL without approval."],
            decision_type=DecisionType.CONSTRAINT,
            dimensions=[Dimension.DATABASE],
            made_by="vt-init",
            project="test",
            source_type=SourceType.SCAN,
        )
        scored = assign_tiers([d], always_count=1)
        content = generate_claude_md(scored)
        assert "Do not introduce PostgreSQL" in content


class TestGenerateClaudeRules:
    def test_generates_rule_files(self, decisions: list[Decision], tmp_path: Path) -> None:
        scored = assign_tiers(decisions, always_count=1, auto_count=10)
        auto = [s for s in scored if s.tier == "auto"]
        if auto:
            paths = generate_claude_rules(scored, tmp_path / "rules")
            assert len(paths) > 0
            for p in paths:
                assert p.suffix == ".md"
                content = p.read_text()
                assert "---" in content  # YAML frontmatter
                assert "globs:" in content
                assert "alwaysApply: false" in content

    def test_creates_output_dir(self, decisions: list[Decision], tmp_path: Path) -> None:
        scored = assign_tiers(decisions, always_count=1, auto_count=10)
        rules_dir = tmp_path / "new" / "rules"
        generate_claude_rules(scored, rules_dir)
        assert rules_dir.is_dir()


class TestGenerateCursorRules:
    def test_generates_mdc_files(self, decisions: list[Decision], tmp_path: Path) -> None:
        scored = assign_tiers(decisions, always_count=2, auto_count=10)
        paths = generate_cursor_rules(scored, tmp_path / "cursor_rules")
        assert len(paths) > 0
        for p in paths:
            assert p.suffix == ".mdc"
            content = p.read_text()
            assert "---" in content

    def test_always_tier_gets_always_apply(self, decisions: list[Decision], tmp_path: Path) -> None:
        scored = assign_tiers(decisions, always_count=5)
        paths = generate_cursor_rules(scored, tmp_path / "rules")
        # All decisions are "always" tier
        for p in paths:
            content = p.read_text()
            assert "alwaysApply: true" in content


class TestGenerateAgentsMd:
    def test_generates_content(self, decisions: list[Decision]) -> None:
        scored = assign_tiers(decisions, always_count=3)
        content = generate_agents_md(scored, project_name="test-project")
        assert "# AGENTS.md" in content
        assert "test-project" in content

    def test_includes_core_rules(self, decisions: list[Decision]) -> None:
        scored = assign_tiers(decisions, always_count=5)
        content = generate_agents_md(scored)
        assert "Core Rules" in content
        for d in decisions:
            assert d.title in content

    def test_empty_decisions(self) -> None:
        content = generate_agents_md([], project_name="empty")
        assert "No architectural decisions" in content


class TestSyncRules:
    def test_full_sync(self, decisions: list[Decision], config: GovernanceConfig, tmp_path: Path) -> None:
        # Create .smm/generated/ dir
        (tmp_path / ".smm" / "generated").mkdir(parents=True)
        result = sync_rules(decisions, tmp_path, config)
        assert len(result.files_written) > 0
        assert result.always_count + result.auto_count + result.on_demand_count == len(decisions)

    def test_creates_agents_md_at_root(self, decisions: list[Decision], config: GovernanceConfig, tmp_path: Path) -> None:
        (tmp_path / ".smm" / "generated").mkdir(parents=True)
        sync_rules(decisions, tmp_path, config)
        assert (tmp_path / "AGENTS.md").is_file()
        content = (tmp_path / "AGENTS.md").read_text()
        assert "AGENTS.md" in content

    def test_creates_claude_files_when_enabled(self, decisions: list[Decision], tmp_path: Path) -> None:
        config = GovernanceConfig(agents={"claude": True, "cursor": False})
        (tmp_path / ".smm" / "generated").mkdir(parents=True)
        result = sync_rules(decisions, tmp_path, config)
        generated_claude = [f for f in result.files_written if "CLAUDE.md" in f.name]
        assert len(generated_claude) > 0

    def test_skips_cursor_when_disabled(self, decisions: list[Decision], tmp_path: Path) -> None:
        config = GovernanceConfig(agents={"claude": False, "cursor": False})
        (tmp_path / ".smm" / "generated").mkdir(parents=True)
        result = sync_rules(decisions, tmp_path, config)
        cursor_files = [f for f in result.files_written if ".cursor" in str(f)]
        assert len(cursor_files) == 0


# ---------------------------------------------------------------------------
# Bug 2: vt apply duplicates CLAUDE.md content
# ---------------------------------------------------------------------------


class TestWriteRootClaudeMd:
    """_write_root_claude_md must always use markers and never duplicate."""

    def test_new_file_has_markers(self, tmp_path: Path) -> None:
        """When CLAUDE.md doesn't exist, it should be written WITH markers."""
        path = tmp_path / "CLAUDE.md"
        _write_root_claude_md(path, "# Rules\nDo not use MongoDB.")

        content = path.read_text()
        assert _GOVERNANCE_START in content
        assert _GOVERNANCE_END in content
        assert content.count("Do not use MongoDB.") == 1

    def test_idempotent_no_duplication(self, tmp_path: Path) -> None:
        """Running twice should NOT duplicate content."""
        path = tmp_path / "CLAUDE.md"
        rules = "# Rules\nDo not use MongoDB."

        _write_root_claude_md(path, rules)
        first = path.read_text()

        _write_root_claude_md(path, rules)
        second = path.read_text()

        assert first == second
        assert second.count("Do not use MongoDB.") == 1
        assert second.count(_GOVERNANCE_START) == 1
        assert second.count(_GOVERNANCE_END) == 1

    def test_preserves_existing_content_outside_markers(self, tmp_path: Path) -> None:
        """User content outside markers must be preserved."""
        path = tmp_path / "CLAUDE.md"
        path.write_text("# My Project\n\nCustom instructions here.\n")

        _write_root_claude_md(path, "# Governance\nUse PostgreSQL.")

        content = path.read_text()
        assert "Custom instructions here." in content
        assert "Use PostgreSQL." in content
        assert _GOVERNANCE_START in content
        assert content.count("Use PostgreSQL.") == 1

    def test_replaces_between_markers(self, tmp_path: Path) -> None:
        """Existing governance section should be replaced, not appended."""
        path = tmp_path / "CLAUDE.md"
        path.write_text(
            "# My Project\n\n"
            f"{_GOVERNANCE_START}\nOLD RULES\n{_GOVERNANCE_END}\n\n"
            "# Footer\n"
        )

        _write_root_claude_md(path, "NEW RULES")

        content = path.read_text()
        assert "OLD RULES" not in content
        assert "NEW RULES" in content
        assert "# My Project" in content
        assert "# Footer" in content
        assert content.count(_GOVERNANCE_START) == 1

    def test_full_sync_idempotent(self, decisions: list[Decision], tmp_path: Path) -> None:
        """Full sync_rules called twice should not duplicate CLAUDE.md content."""
        config = GovernanceConfig(agents={"claude": True, "cursor": False})
        (tmp_path / ".smm" / "generated").mkdir(parents=True)

        sync_rules(decisions, tmp_path, config)
        first = (tmp_path / "CLAUDE.md").read_text()

        sync_rules(decisions, tmp_path, config)
        second = (tmp_path / "CLAUDE.md").read_text()

        assert first == second
        assert second.count(_GOVERNANCE_START) == 1

    def test_full_sync_with_existing_claude_md(self, decisions: list[Decision], tmp_path: Path) -> None:
        """Sync with existing CLAUDE.md should preserve user content."""
        config = GovernanceConfig(agents={"claude": True, "cursor": False})
        (tmp_path / ".smm" / "generated").mkdir(parents=True)

        # User's existing CLAUDE.md
        (tmp_path / "CLAUDE.md").write_text("# My Custom Rules\n\nDo not touch auth.\n")

        sync_rules(decisions, tmp_path, config)
        content = (tmp_path / "CLAUDE.md").read_text()

        assert "My Custom Rules" in content
        assert "Do not touch auth." in content
        assert _GOVERNANCE_START in content
        assert content.count(_GOVERNANCE_START) == 1


class TestWriteRootAgentFile:
    """Same marker logic for AGENTS.md."""

    def test_new_file_has_markers(self, tmp_path: Path) -> None:
        path = tmp_path / "AGENTS.md"
        _write_root_agent_file(path, "# Agent Rules")

        content = path.read_text()
        assert _GOVERNANCE_START in content
        assert _GOVERNANCE_END in content

    def test_idempotent_no_duplication(self, tmp_path: Path) -> None:
        path = tmp_path / "AGENTS.md"
        rules = "# Agent Rules"

        _write_root_agent_file(path, rules)
        _write_root_agent_file(path, rules)

        content = path.read_text()
        assert content.count("Agent Rules") == 1
        assert content.count(_GOVERNANCE_START) == 1
