"""GitHub App PR comments — architecture review on every PR.

Posts architecture review comments on pull requests, showing:
- Decisions introduced or touched by the PR
- Contradictions detected
- Dependency scope check
- Architecture coherence score

Updates existing comments rather than posting new ones (find by bot marker).

From SPEC: "GitHub App — post architecture review comment on every PR.
Edit existing comments rather than posting new ones."
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

import httpx

logger = logging.getLogger(__name__)

# Marker to identify our comments for edit-not-create behavior
BOT_MARKER = "<!-- vt-protocol-review -->"

COMMENT_TEMPLATE = """\
{marker}
## VT Protocol — Architecture Review

{status_badge}

### Decisions
{decisions_section}

### Contradictions
{contradictions_section}

### Dependency Check
{dependency_section}

### Coherence Score
{coherence_section}

---
*Generated by [VT Protocol](https://github.com/varunajaytawde/vt-protocol)*
"""


@dataclass
class ReviewResult:
    """Data for a PR architecture review."""

    decisions_introduced: list[dict[str, str]] = field(default_factory=list)
    decisions_touched: list[dict[str, str]] = field(default_factory=list)
    contradictions: list[dict[str, str]] = field(default_factory=list)
    new_dependencies: list[str] = field(default_factory=list)
    max_deps_per_task: int = 3
    coherence_score: float = 1.0  # 0.0-1.0

    @property
    def has_violations(self) -> bool:
        return bool(self.contradictions) or len(self.new_dependencies) > self.max_deps_per_task

    @property
    def status(self) -> str:
        if self.has_violations:
            return "fail"
        return "pass"


def format_review_comment(review: ReviewResult) -> str:
    """Format a ReviewResult into a Markdown comment body."""
    status_badge = (
        "**Status: PASS** — No governance violations detected."
        if not review.has_violations
        else "**Status: FAIL** — Governance violations found."
    )

    # Decisions section
    if review.decisions_introduced or review.decisions_touched:
        dec_lines = []
        for d in review.decisions_introduced:
            dec_lines.append(f"- **NEW:** {d.get('title', 'Untitled')} ({d.get('type', 'technical')})")
        for d in review.decisions_touched:
            dec_lines.append(f"- **Touched:** {d.get('title', 'Untitled')}")
        decisions_section = "\n".join(dec_lines)
    else:
        decisions_section = "No architectural decisions detected in this PR."

    # Contradictions section
    if review.contradictions:
        contra_lines = []
        for c in review.contradictions:
            contra_lines.append(
                f"- **{c.get('verdict', 'unknown').upper()}:** "
                f"{c.get('decision_a', '?')} vs {c.get('decision_b', '?')} "
                f"(confidence: {c.get('confidence', '?')})"
            )
        contradictions_section = "\n".join(contra_lines)
    else:
        contradictions_section = "No contradictions detected."

    # Dependency section
    dep_count = len(review.new_dependencies)
    dep_ok = dep_count <= review.max_deps_per_task
    if review.new_dependencies:
        dep_list = ", ".join(review.new_dependencies)
        dependency_section = (
            f"{'✓' if dep_ok else '✗'} {dep_count} new dependencies "
            f"(max {review.max_deps_per_task}): {dep_list}"
        )
    else:
        dependency_section = "No new dependencies detected."

    # Coherence section
    pct = int(review.coherence_score * 100)
    coherence_section = f"Architecture coherence: **{pct}%**"

    return COMMENT_TEMPLATE.format(
        marker=BOT_MARKER,
        status_badge=status_badge,
        decisions_section=decisions_section,
        contradictions_section=contradictions_section,
        dependency_section=dependency_section,
        coherence_section=coherence_section,
    )


async def post_or_update_comment(
    owner: str,
    repo: str,
    pr_number: int,
    body: str,
    *,
    token: str,
    api_base: str = "https://api.github.com",
) -> dict:
    """Post a new comment or update existing one on a PR.

    Finds existing comment by BOT_MARKER to avoid duplicate comments.
    Returns the comment data dict from the GitHub API.
    """
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient(base_url=api_base, headers=headers) as client:
        # Find existing comment
        existing_id = await _find_existing_comment(client, owner, repo, pr_number)

        if existing_id:
            # Update existing comment
            resp = await client.patch(
                f"/repos/{owner}/{repo}/issues/comments/{existing_id}",
                json={"body": body},
            )
        else:
            # Create new comment
            resp = await client.post(
                f"/repos/{owner}/{repo}/issues/{pr_number}/comments",
                json={"body": body},
            )

        resp.raise_for_status()
        return resp.json()


async def create_check_run(
    owner: str,
    repo: str,
    head_sha: str,
    review: ReviewResult,
    *,
    token: str,
    api_base: str = "https://api.github.com",
) -> dict:
    """Create a GitHub check run for merge gating.

    Sets conclusion to "success" or "failure" based on review result.
    """
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    check_data = {
        "name": "VT Protocol — Architecture Review",
        "head_sha": head_sha,
        "status": "completed",
        "conclusion": "success" if not review.has_violations else "failure",
        "output": {
            "title": "Architecture Review",
            "summary": (
                f"Coherence: {int(review.coherence_score * 100)}% | "
                f"Contradictions: {len(review.contradictions)} | "
                f"New deps: {len(review.new_dependencies)}"
            ),
        },
    }

    async with httpx.AsyncClient(base_url=api_base, headers=headers) as client:
        resp = await client.post(
            f"/repos/{owner}/{repo}/check-runs",
            json=check_data,
        )
        resp.raise_for_status()
        return resp.json()


async def _find_existing_comment(
    client: httpx.AsyncClient,
    owner: str,
    repo: str,
    pr_number: int,
) -> int | None:
    """Find our existing comment by BOT_MARKER. Returns comment ID or None."""
    resp = await client.get(
        f"/repos/{owner}/{repo}/issues/{pr_number}/comments",
        params={"per_page": 100},
    )
    resp.raise_for_status()

    for comment in resp.json():
        body = comment.get("body", "")
        if BOT_MARKER in body:
            return comment["id"]

    return None
